# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5ec424ade14dca6496cd6f81c00cb6da48f05c7ed64099c870e550871cd1805809d7d68e6d3c837da088e0ffbb3692f1f3bd0544c8015e80d5451f0d6643af

test:
  secret_key_base: 6274d794e139509ecb2e54a1a99f447c3e291b34c3b6dc565f28a73163019f5ec69f8a0f5d5fc15da7e652890b2ec81c745d7214763ae1efe04e933c825f55c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
